version: '3ß'

services:
  app:
    image: sidelog
    build: .
    environment:
      NODE_ENV: development
      CONFIG_PATH: /app/config-dev/docker-mongo.config.json
    ports:
      - 3000:3000
    volumes:
      - .:/app
    links:
      - mongodb
    command: sh -c "npm run watch"

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
